### ISSUE TITLE
usb.core.USBError: [Errno 13] Access denied (insufficient permissions)

### ISSUE THREAD

**Issue by mvillarejo** [codedance/Retaliation#20]
Hello,
I'm getting this error whilst trying to run any command in OS X (Mavericks 10.9.5), even running it as root... does not seem to work, cheers

**Comment by wpillar** [comment]
Same here, found nothing online that helps...

**Comment by jtheoof** [comment]
I am having the same issue on `OS X 10.10.3 (Yosemite)`.

**Comment by alex3137** [comment]
Same problem, any clue ?

**Comment by codedance** [comment]
I haven't managed to duplicate this as we're running the code on a Raspberry Pi and Windows, and I've only tested on an older Mac.  I did come across this thread that seemed related:

https://github.com/Yubico/python-yubico/issues/7

**Comment by brianantonelli** [comment]
If you drop `pyusb` and `libusb` and use `hidapi` this works perfect.

Just install hidapi: `pip install hidapi`

And replace pyusb references with:
```
hidraw = hid.device(0x2123, 0x1010)
hidraw.open(0x2123, 0x1010)
hidraw.send_feature_report([0x02, 0x10, 0x00,0x00,0x00,0x00,0x00,0x00])
```

The above code will connect to the device and send a fire command.

**Comment by mvillarejo** [comment]
Thanks, closing this now, I don't even have it now :)
