### ISSUE TITLE
Wont "Fire"

### ISSUE THREAD

**Issue by RogueIMP** [codedance/Retaliation#21]
I got it working in Windows7, with a few minor alterations (updating for Python 3.4), and on my Raspberry Pi (wheezy).  Everything works on both, but the Fire command.  It worked in Windows twice, then stopped, and hasn't worked in Raspbian at all.
Any suggestions?

**Comment by starryknight64** [comment]
Does it fire when using the THUNDER program that comes with it still? Mine
fired once and then the hardware itself died and so I had to get it
replaced.

**Comment by RogueIMP** [comment]
It works off and on with the original program (which is junk).  I just
submitted a replacement from ThinkGeek.  I'll let you know how this 2nd one
does.  THanks for the heads up!

**Comment by starryknight64** [comment]
They take some time to do returns for whatever reason. Once they had it processed they just sent me a new one and didn't need to send the old one back.

**Comment by codedance** [comment]
Mine is still going strong many broken builds later.  A few lost misses though!
